/*global systemDictionary:true */
/*

*/



'use strict';

systemDictionary = {
    'Main settings': {
        "en": "Main settings",
    "de": "Haupteinstellungen",
    "ru": "Основные настройки",
    "pt": "Configurações principais",
    "nl": "Belangrijkste instellingen",
    "fr": "Réglages principaux",
    "it": "Impostazioni principali",
    "es": "Ajustes principales",
    "pl": "Ustawienia główne",
    "zh-cn": "主要设定"  
    },
    'Blacklist': {
        "en": "Blacklist",
    "de": "Schwarze Liste",
    "ru": "Черный список",
    "pt": "Lista negra",
    "nl": "Zwarte lijst",
    "fr": "Liste noire",
    "it": "Lista nera",
    "es": "Lista negra",
    "pl": "Czarna lista",
    "zh-cn": "黑名单" 
    },
    'Syncronisation': {
        "en": "Syncronisation",
    "de": "Synchronisation",
    "ru": "Syncronisation",
    "pt": "Sincronização",
    "nl": "Syncronisatie",
    "fr": "Syncronisation",
    "it": "syncronisation",
    "es": "Sincronización",
    "pl": "Synchronizacja",
    "zh-cn": "同步化"
    },
    'Polling interval (ms) use more than 60000 pls.': {
        "en": "Polling interval (ms) use more than 60.000 pls.",
    "de": "Das Abfrageintervall (ms) verwendet mehr als 60.000 bitte.",
    "ru": "Интервал опроса (мс) использовать более 60.000 PLS.",
    "pt": "O intervalo de pesquisa (ms) usa mais de 60.000 pls.",
    "nl": "Polling-interval (ms) gebruikt meer dan 60.000 pls.",
    "fr": "L'intervalle d'interrogation (ms) utilise plus de 60 000 pls.",
    "it": "L'intervallo di polling (ms) utilizza più di 60.000 pls.",
    "es": "El intervalo de sondeo (ms) usa más de 60,000 pls.",
    "pl": "Interwał sondowania (ms) użyj ponad 60 000 wiadomości.",
    "zh-cn": "轮询间隔（ms）使用超过60.000 pls。"
    },
    'token': {
        "en": "token for Api from Todoist",
    "de": "Token für Api von Todoist",
    "ru": "токен для Api от Todoist",
    "pt": "token para Api de Todoist",
    "nl": "token voor Api van Todoist",
    "fr": "jeton pour Api de Todoist",
    "it": "token per Api di Todoist",
    "es": "ficha para Api de Todoist",
    "pl": "token dla Api z Todoist",
    "zh-cn": "Todoist的Api代币"
    },
    'Read README.md how to get token': {
        "en": "click here to get token",
    "de": "Klicken Sie hier, um den Token zu erhalten",
    "ru": "нажмите здесь, чтобы получить токен",
    "pt": "clique aqui para obter o token",
    "nl": "klik hier om een token te krijgen",
    "fr": "cliquez ici pour obtenir un jeton",
    "it": "fai clic qui per ottenere il token",
    "es": "haga clic aquí para obtener el token",
    "pl": "kliknij tutaj, aby uzyskać token",
    "zh-cn": "单击此处获取令牌"
    },
    'Einstellungen': {
        "en": "Settings",
    "de": "Einstellungen",
    "ru": "настройки",
    "pt": "Definições",
    "nl": "Instellingen",
    "fr": "Réglages",
    "it": "impostazioni",
    "es": "Configuraciones",
    "pl": "Ustawienia",
    "zh-cn": "设定值"
    },
    'debug': {
        "en": "debug",
    "de": "debuggen",
    "ru": "отлаживать",
    "pt": "depurar",
    "nl": "debuggen",
    "fr": "déboguer",
    "it": "mettere a punto",
    "es": "depurar",
    "pl": "odpluskwić",
    "zh-cn": "调试"
    },
    'debug mode on': {
        "en": "debug mode on",
    "de": "Debug-Modus ein",
    "ru": "режим отладки включен",
    "pt": "modo de depuração ativado",
    "nl": "debug-modus aan",
    "fr": "mode débogage activé",
    "it": "modalità di debug attivata",
    "es": "modo de depuración en",
    "pl": "włączony tryb debugowania",
    "zh-cn": "打开调试模式"
    },
    'Dublikate': {
        "en": "Duplicates",
    "de": "Duplikate",
    "ru": "Дубликаты",
    "pt": "Duplicatas",
    "nl": "Duplicaten",
    "fr": "Doublons",
    "it": "duplicati",
    "es": "Duplicados",
    "pl": "Duplikaty",
    "zh-cn": "重复项"
    },
    'Bereits angelegte Tasks (Dublikate) nicht erneut anlegen': {
        "en": "Do not re-create tasks (duplicates) that have already been created",
        "de": "Bereits angelegte Tasks (Dublikate) nicht erneut anlegen",
        "ru": "Не создавать заново задачи (дубликаты), которые уже были созданы",
        "pt": "Não recrie tarefas (duplicatas) que já foram criadas",
        "nl": "Maak geen taken (duplicaten) opnieuw die al zijn gemaakt",
        "fr": "Ne recréez pas les tâches (doublons) qui ont déjà été créées",
        "it": "Non ricreare attività (duplicati) che sono già state create",
        "es": "No vuelva a crear tareas (duplicados) que ya se hayan creado.",
        "pl": "Nie twórz ponownie zadań (duplikatów), które zostały już utworzone",
        "zh-cn": "不要重新创建已经创建的任务（重复项）"
    },
    'Remove old Objekts': {
        "en": "Remove old Objects",
    "de": "Alte Objekte entfernen",
    "ru": "Удалить старые объекты",
    "pt": "Remover objetos antigos",
    "nl": "Verwijder oude objecten",
    "fr": "Supprimer les anciens objets",
    "it": "Rimuovi vecchi oggetti",
    "es": "Eliminar objetos viejos",
    "pl": "Usuń stare obiekty",
    "zh-cn": "删除旧对象"
    },
    'Alte Objekte werden automatisch, ja nach Intravall, gelöscht. (BETA!!!)': {
        "en": "Old objects are deleted automatically, depending on the intravall. (BETA!!!)",
    "de": "Alte Objekte werden je nach Intravall automatisch gelöscht. (BETA!!!)",
    "ru": "Старые объекты удаляются автоматически, в зависимости от интравалла. (БЕТА!!!)",
    "pt": "Objetos antigos são excluídos automaticamente, dependendo do intravall. (BETA!!!)",
    "nl": "Oude objecten worden automatisch verwijderd, afhankelijk van de intravall. (BÈTA !!!)",
    "fr": "Les anciens objets sont supprimés automatiquement, selon l'intravall. (BÊTA!!!)",
    "it": "I vecchi oggetti vengono eliminati automaticamente, a seconda dell'intravall. (BETA!!!)",
    "es": "Los objetos antiguos se eliminan automáticamente, según la intravall. (¡¡¡BETA!!!)",
    "pl": "Stare obiekty są usuwane automatycznie, w zależności od instalacji wewnętrznej. (BETA !!!)",
    "zh-cn": "旧对象会自动删除，具体取决于时间间隔。 （BETA !!!）"
    },
    'Auswahl Anlage Objekte': {
        "en": "Selection of objects",
    "de": "Auswahl von Objekten",
    "ru": "Подбор объектов",
    "pt": "Seleção de objetos",
    "nl": "Selectie van objecten",
    "fr": "Sélection d'objets",
    "it": "Selezione di oggetti",
    "es": "Selección de objetos.",
    "pl": "Wybór obiektów",
    "zh-cn": "选择对象"
    },
    'Project': {
        "en": "Project",
    "de": "Projekte",
    "ru": "проект",
    "pt": "Projeto",
    "nl": "Project",
    "fr": "Projet",
    "it": "Progetto",
    "es": "Proyecto",
    "pl": "Projekt",
    "zh-cn": "项目"
    },
    'Projekte als Objekte anlegen': {
        "en": "Create projects as objects",
    "de": "Erstellen Sie Projekte als Objekte",
    "ru": "Создавайте проекты как объекты",
    "pt": "Crie projetos como objetos",
    "nl": "Maak projecten als objecten",
    "fr": "Créer des projets en tant qu'objets",
    "it": "Crea progetti come oggetti",
    "es": "Crea proyectos como objetos",
    "pl": "Twórz projekty jako obiekty",
    "zh-cn": "将项目创建为对象"
    },
    'Section': {
        "en": "Section",
        "de": "Sektion",
        "ru": "Раздел",
        "pt": "Seção",
        "nl": "Sectie",
        "fr": "Section",
        "it": "Sezione",
        "es": "Sección",
        "pl": "Sekcja",
        "zh-cn": "部分"
    },
    'Section als Objekte anlegen': {
        "en": "Create section as objects",
    "de": "Abschnitt als Objekte erstellen",
    "ru": "Создать раздел как объекты",
    "pt": "Criar seção como objetos",
    "nl": "Maak sectie als objecten",
    "fr": "Créer une section en tant qu'objets",
    "it": "Crea sezione come oggetti",
    "es": "Crear sección como objetos",
    "pl": "Utwórz sekcję jako obiekty",
    "zh-cn": "将节创建为对象"
    },
    'Tasks': {
        "en": "Tasks",
    "de": "Aufgaben",
    "ru": "Задания",
    "pt": "Tarefas",
    "nl": "Taken",
    "fr": "Tâches",
    "it": "Compiti",
    "es": "Tareas",
    "pl": "Zadania",
    "zh-cn": "任务"
    },
    'Tasks als Objekte anlegen': {
        "en": "Create tasks as objects",
    "de": "Erstellen Sie Aufgaben als Objekte",
    "ru": "Создавайте задачи как объекты",
    "pt": "Criar tarefas como objetos",
    "nl": "Maak taken als objecten",
    "fr": "Créer des tâches en tant qu'objets",
    "it": "Crea attività come oggetti",
    "es": "Crea tareas como objetos",
    "pl": "Twórz zadania jako obiekty",
    "zh-cn": "将任务创建为对象"
    },
    'Labels': {
        "en": "Labels",
    "de": "Labels",
    "ru": "Этикетки",
    "pt": "Etiquetas",
    "nl": "Etiketten",
    "fr": "Étiquettes",
    "it": "etichette",
    "es": "Etiquetas",
    "pl": "Etykiety",
    "zh-cn": "标签"
    },
    'Labels als Objekte anlegen': {
        "en": "Create labels as objects",
    "de": "Erstellen Sie Beschriftungen als Objekte",
    "ru": "Создать ярлыки как объекты",
    "pt": "Crie etiquetas como objetos",
    "nl": "Maak labels als objecten",
    "fr": "Créer des étiquettes en tant qu'objets",
    "it": "Crea etichette come oggetti",
    "es": "Crea etiquetas como objetos",
    "pl": "Twórz etykiety jako obiekty",
    "zh-cn": "将标签创建为对象"
    },
    'Art der Objekte': {
        "en": "Type of objects",
        "de": "Art der Objekte",
        "ru": "Тип объектов",
        "pt": "Tipo de objetos",
        "nl": "Type objecten",
        "fr": "Type d'objets",
        "it": "Tipo di oggetti",
        "es": "Tipo de objetos",
        "pl": "Rodzaj obiektów",
        "zh-cn": "对象类型"
    },
    'HTML': {
        "en": "HTML",
    "de": "HTML",
    "ru": "HTML",
    "pt": "HTML",
    "nl": "HTML",
    "fr": "HTML",
    "it": "HTML",
    "es": "HTML",
    "pl": "HTML",
    "zh-cn": "的HTML"
    },
    'HTML Objekte anlegen': {
        "en": "Create HTML objects",
    "de": "Erstellen Sie HTML-Objekte",
    "ru": "Создать HTML-объекты",
    "pt": "Crie objetos HTML",
    "nl": "Maak HTML-objecten",
    "fr": "Créer des objets HTML",
    "it": "Crea oggetti HTML",
    "es": "Crea objetos HTML",
    "pl": "Twórz obiekty HTML",
    "zh-cn": "创建HTML对象"
    },
    'JSON': {
        "en": "JSON",
    "de": "JSON",
    "ru": "JSON",
    "pt": "JSON",
    "nl": "JSON",
    "fr": "JSON",
    "it": "JSON",
    "es": "JSON",
    "pl": "JSON",
    "zh-cn": "JSON格式"
    },
    'JSON Objekte anlegen': {
        "en": "Create JSON objects",
    "de": "Erstellen Sie JSON-Objekte",
    "ru": "Создать объекты JSON",
    "pt": "Criar objetos JSON",
    "nl": "Maak JSON-objecten",
    "fr": "Créer des objets JSON",
    "it": "Crea oggetti JSON",
    "es": "Crear objetos JSON",
    "pl": "Utwórz obiekty JSON",
    "zh-cn": "创建JSON对象"
    },
    'Text': {
        "en": "Text",
    "de": "Text",
    "ru": "Текст",
    "pt": "Texto",
    "nl": "Tekst",
    "fr": "Texte",
    "it": "Testo",
    "es": "Texto",
    "pl": "Tekst",
    "zh-cn": "文本"
    },
    'Text Objekte anlegen': {
        "en": "Create text objects",
    "de": "Erstellen Sie Textobjekte",
    "ru": "Создать текстовые объекты",
    "pt": "Crie objetos de texto",
    "nl": "Maak tekstobjecten",
    "fr": "Créer des objets texte",
    "it": "Crea oggetti di testo",
    "es": "Crea objetos de texto",
    "pl": "Twórz obiekty tekstowe",
    "zh-cn": "创建文本对象"
    },
    'Blacklist: Hier kannst du Blacklist für die einzelnen Bereiche anlegen.': {
        "en": "Blacklist: Here you can create a blacklist for the individual objects.",
    "de": "Blacklist: Hier können Sie eine Blacklist für die einzelnen Objekte erstellen.",
    "ru": "Черный список: здесь вы можете создать черный список для отдельных объектов.",
    "pt": "Lista negra: aqui você pode criar uma lista negra para os objetos individuais.",
    "nl": "Zwarte lijst: hier kunt u een zwarte lijst maken voor de afzonderlijke objecten.",
    "fr": "Liste noire: Ici, vous pouvez créer une liste noire pour les objets individuels.",
    "it": "Lista nera: qui puoi creare una lista nera per i singoli oggetti.",
    "es": "Lista negra: aquí puede crear una lista negra para los objetos individuales.",
    "pl": "Czarna lista: tutaj możesz utworzyć czarną listę dla poszczególnych obiektów.",
    "zh-cn": "黑名单：您可以在此处为单个对象创建黑名单。"
    },
    'Syncronisation: Hier kannst du Projekte miteinander Syncornisieren.': {
        "en": "Synchronization: Here you can synchronize projects with each other",
    "de": "Synchronisation: Hier können Sie Projekte miteinander synchronisieren",
    "ru": "Синхронизация: здесь вы можете синхронизировать проекты друг с другом",
    "pt": "Sincronização: aqui você pode sincronizar projetos entre si",
    "nl": "Synchronisatie: Hier kunt u projecten met elkaar synchroniseren",
    "fr": "Synchronisation: ici, vous pouvez synchroniser des projets entre eux",
    "it": "Sincronizzazione: qui è possibile sincronizzare i progetti tra loro",
    "es": "Sincronización: aquí puede sincronizar proyectos entre sí",
    "pl": "Synchronizacja: tutaj możesz synchronizować projekty ze sobą",
    "zh-cn": "同步：在这里您可以彼此同步项目"
    },
    'Dublikate können nicht erkannt werden! Bitte Auto delete nutzen, sonst werden ganz viele Todos angelegt.': {
        "en": "Duplicates cannot be recognized! Please use Auto delete, otherwise a lot of todos will be created.",
        "de": "Duplikate können nicht erkannt werden! Bitte verwenden Sie Automatisch löschen, da sonst viele Aufgaben erstellt werden.",
        "ru": "Дубликаты не могут быть распознаны! Пожалуйста, используйте Автоудаление, в противном случае будет создано много задач.",
        "pt": "Duplicatas não podem ser reconhecidas! Por favor, use Exclusão automática, caso contrário, muitos serão criados.",
        "nl": "Duplicaten worden niet herkend! Gebruik a.u.b.Automatisch verwijderen, anders worden er veel taken gemaakt.",
        "fr": "Les doublons ne peuvent pas être reconnus! Veuillez utiliser la suppression automatique, sinon beaucoup de tâches seront créées.",
        "it": "I duplicati non possono essere riconosciuti! Utilizza l'eliminazione automatica, altrimenti verranno creati molti todos.",
        "es": "¡Los duplicados no se pueden reconocer! Utilice la eliminación automática, de lo contrario se crearán muchos todos.",
        "pl": "Duplikatów nie można rozpoznać! Skorzystaj z automatycznego usuwania, w przeciwnym razie powstanie wiele rzeczy do zrobienia.",
        "zh-cn": "无法识别重复项！请使用自动删除，否则将创建很多待办事项。"
    },
    'Projekt ID Quelle': {
        "en": "Project ID source",
    "de": "Projekt-ID-Quelle",
    "ru": "Источник идентификатора проекта",
    "pt": "Origem do ID do projeto",
    "nl": "Bron van project-ID",
    "fr": "Source d'ID de projet",
    "it": "Origine ID progetto",
    "es": "Fuente de identificación del proyecto",
    "pl": "Źródło identyfikatora projektu",
    "zh-cn": "项目ID来源"
    },
    'Projekt ID Ziel': {
        "en": "Project ID target",
    "de": "Projekt-ID-Ziel",
    "ru": "ID проекта",
    "pt": "Destino do ID do projeto",
    "nl": "Doel van project-ID",
    "fr": "Cible d'ID de projet",
    "it": "Target ID progetto",
    "es": "ID del proyecto objetivo",
    "pl": "Docelowy identyfikator projektu",
    "zh-cn": "项目ID目标"
    },
    'Comment': {
        "en": "comment",
    "de": "Kommentar",
    "ru": "комментарий",
    "pt": "Comente",
    "nl": "commentaar",
    "fr": "commentaire",
    "it": "commento",
    "es": "comentario",
    "pl": "komentarz",
    "zh-cn": "评论"
    },
    'Projekt ID': {
        "en": "Project ID",
    "de": "Projekt-ID",
    "ru": "Идентификатор проекта",
    "pt": "ID do projeto",
    "nl": "Project-ID",
    "fr": "ID du projet",
    "it": "ID progetto",
    "es": "Projecto ID",
    "pl": "ID projektu",
    "zh-cn": "专案编号"
  
    },
    'Art': {
        "en": "type",
    "de": "Art",
    "ru": "тип",
    "pt": "tipo",
    "nl": "type",
    "fr": "type",
    "it": "genere",
    "es": "tipo",
    "pl": "rodzaj",
    "zh-cn": "类型"
    },
    "Filter List: Das ist ein Premium Feature von Todoist. Du musst Todoist Premium kaufen um diesen nutzen zu können.": {
        "en": "Filter List: This is a premium feature from Todoist. You have to buy Todoist Premium to use it.",
        "de": "Filterliste: Dies ist eine Premium-Funktion von Todoist. Sie müssen Todoist Premium kaufen, um es zu verwenden.",
        "ru": "Список фильтров: это премиум-функция от Todoist. Вы должны купить Todoist Premium, чтобы использовать его.",
        "pt": "Lista de filtros: esse é um recurso premium do Todoist. Você precisa comprar Todoist Premium para usá-lo.",
        "nl": "Filterlijst: dit is een premiumfunctie van Todoist. Je moet Todoist Premium kopen om het te gebruiken.",
        "fr": "Liste de filtres: il s'agit d'une fonctionnalité premium de Todoist. Vous devez acheter Todoist Premium pour l'utiliser.",
        "it": "Elenco filtri: questa è una funzionalità premium di Todoist. Devi acquistare Todoist Premium per usarlo.",
        "es": "Lista de filtros: esta es una característica premium de Todoist. Tienes que comprar Todoist Premium para usarlo.",
        "pl": "Filtruj listę: Jest to funkcja premium od Todoist. Aby go użyć, musisz kupić Todoist Premium.",
        "zh-cn": "筛选器列表：这是Todoist的一项高级功能。您必须购买Todoist Premium才能使用。"
      },
      "Filter aktivieren": {
        "en": "Activate filter",
        "de": "Filter aktivieren",
        "ru": "Активировать фильтр",
        "pt": "Ativar filtro",
        "nl": "Activeer filter",
        "fr": "Activer le filtre",
        "it": "Attiva il filtro",
        "es": "Activar filtro",
        "pl": "Aktywuj filtr",
        "zh-cn": "激活过滤器"
      },
      "Erklärung zu Filter": {
        "en": "Explanation of filters",
        "de": "Erklärung der Filter",
        "ru": "Объяснение фильтров",
        "pt": "Explicação dos filtros",
        "nl": "Uitleg van filters",
        "fr": "Explication des filtres",
        "it": "Spiegazione dei filtri",
        "es": "Explicación de los filtros.",
        "pl": "Objaśnienie filtrów",
        "zh-cn": "过滤器说明"
      },
      "Die Filter Liste erlaubt es eigene Listen zu erstellen. Beispiel: heute, morgen, letze 7 Tage, usw.": {
        "en": "The filter list allows you to create your own lists. Example: today, tomorrow, last 7 days, etc.",
        "de": "Mit der Filterliste können Sie Ihre eigenen Listen erstellen. Beispiel: heute, morgen, letzte 7 Tage usw.",
        "ru": "Список фильтров позволяет создавать свои собственные списки. Пример: сегодня, завтра, последние 7 дней и т. Д.",
        "pt": "A lista de filtros permite que você crie suas próprias listas. Exemplo: hoje, amanhã, últimos 7 dias, etc.",
        "nl": "Met de filterlijst kunt u uw eigen lijsten maken. Voorbeeld: vandaag, morgen, laatste 7 dagen, etc.",
        "fr": "La liste de filtres vous permet de créer vos propres listes. Exemple: aujourd'hui, demain, 7 derniers jours, etc.",
        "it": "L'elenco filtri consente di creare elenchi personalizzati. Esempio: oggi, domani, ultimi 7 giorni, ecc.",
        "es": "La lista de filtros le permite crear sus propias listas. Ejemplo: hoy, mañana, últimos 7 días, etc.",
        "pl": "Lista filtrów pozwala tworzyć własne listy. Przykład: dzisiaj, jutro, ostatnie 7 dni itp.",
        "zh-cn": "过滤器列表允许您创建自己的列表。例如：今天，明天，过去7天，等等。"
      },
      "Filter Name": {
        "en": "Filter name",
        "de": "Filtername",
        "ru": "Название фильтра",
        "pt": "Nome do filtro",
        "nl": "Filternaam",
        "fr": "Nom du filtre",
        "it": "Nome del filtro",
        "es": "Nombre del filtro",
        "pl": "Nazwa filtra",
        "zh-cn": "筛选器名称"
      },
      "Filter Query": {
        "en": "Filter query",
        "de": "Filterabfrage",
        "ru": "Фильтр запроса",
        "pt": "Filtrar consulta",
        "nl": "Filterquery",
        "fr": "Filtrer la requête",
        "it": "Filtro query",
        "es": "Consulta de filtro",
        "pl": "Filtruj zapytanie",
        "zh-cn": "筛选查询"
      },
      "Einstellungen Listen:": {
        "en": "List settings:",
        "de": "Listeneinstellungen:",
        "ru": "Настройки списка:",
        "pt": "Configurações da lista:",
        "nl": "Lijstinstellingen:",
        "fr": "Liste des paramètres:",
        "it": "Impostazioni elenco:",
        "es": "Configuración de la lista:",
        "pl": "Ustawienia listy:",
        "zh-cn": "清单设定："
      },
      "Hier können Sie die Einstellungen der Listen ändern": {
        "en": "Here you can change the settings of the lists",
        "de": "Hier können Sie die Einstellungen der Listen ändern",
        "ru": "Здесь вы можете изменить настройки списков",
        "pt": "Aqui você pode alterar as configurações das listas",
        "nl": "Hier kunt u de instellingen van de lijsten wijzigen",
        "fr": "Ici, vous pouvez modifier les paramètres des listes",
        "it": "Qui è possibile modificare le impostazioni degli elenchi",
        "es": "Aquí puede cambiar la configuración de las listas",
        "pl": "Tutaj możesz zmienić ustawienia list",
        "zh-cn": "在这里您可以更改列表的设置"
      },
      "Einstellung HTML": {
        "en": "HTML setting",
        "de": "HTML-Einstellung",
        "ru": "Настройка HTML",
        "pt": "Configuração HTML",
        "nl": "HTML-instelling",
        "fr": "Paramètre HTML",
        "it": "Impostazione HTML",
        "es": "Configuración HTML",
        "pl": "Ustawienie HTML",
        "zh-cn": "HTML设置"
      },
      "CSS für Table": {
        "en": "CSS for table",
        "de": "CSS für Tabelle",
        "ru": "CSS для таблицы",
        "pt": "CSS para tabela",
        "nl": "CSS voor tabel",
        "fr": "CSS pour la table",
        "it": "CSS per tabella",
        "es": "CSS para tabla",
        "pl": "CSS dla tabeli",
        "zh-cn": "表的CSS"
      },
      "CSS für Button": {
        "en": "CSS for button",
        "de": "CSS für Schaltfläche",
        "ru": "CSS для кнопки",
        "pt": "CSS para botão",
        "nl": "CSS voor knop",
        "fr": "CSS pour le bouton",
        "it": "CSS per pulsante",
        "es": "CSS para botón",
        "pl": "CSS dla przycisku",
        "zh-cn": "按钮的CSS"
      },
      "Welche Felder sollen angezeigt werden?": {
        "en": "Which fields should be displayed?",
        "de": "Welche Felder sollen angezeigt werden?",
        "ru": "Какие поля должны отображаться?",
        "pt": "Quais campos devem ser exibidos?",
        "nl": "Welke velden moeten worden weergegeven?",
        "fr": "Quels champs doivent être affichés?",
        "it": "Quali campi devono essere visualizzati?",
        "es": "¿Qué campos deberían mostrarse?",
        "pl": "Które pola powinny zostać wyświetlone?",
        "zh-cn": "应显示哪些字段？"
      },
      "Einstellung JSON": {
        "en": "JSON setting",
        "de": "JSON-Einstellung",
        "ru": "Настройка JSON",
        "pt": "Configuração JSON",
        "nl": "JSON-instelling",
        "fr": "Paramètre JSON",
        "it": "Impostazione JSON",
        "es": "Configuración JSON",
        "pl": "Ustawienie JSON",
        "zh-cn": "JSON设置"
      },
      "Einstellung Text": {
        "en": "Setting text",
        "de": "Text einstellen",
        "ru": "Настройка текста",
        "pt": "Definir texto",
        "nl": "Tekst instellen",
        "fr": "Définition du texte",
        "it": "Impostazione del testo",
        "es": "Establecer texto",
        "pl": "Ustawianie tekstu",
        "zh-cn": "设定文字"
      },
      ", or - or _ or / or what you want": {
        "en": ", or - or _ or / or what you want",
        "de": ", oder - oder _ oder / oder was du willst",
        "ru": "или - или _ или / или что вы хотите",
        "pt": ", ou - ou _ ou / ou o que você deseja",
        "nl": ", of - of _ of / of wat je wilt",
        "fr": ", ou - ou _ ou / ou ce que vous voulez",
        "it": ", oppure - oppure _ o / o ciò che desideri",
        "es": ", o - o _ o / o lo que quieras",
        "pl": ", lub - lub _ lub / lub co chcesz",
        "zh-cn": "或-或_或/或您想要的"
      },
      "Name für Task ID Feld": {
        "en": "Name for Task ID field",
        "de": "Anzeige für das Feld Aufgaben-ID",
        "ru": "Имя для поля ID задачи",
        "pt": "Nome para o campo ID da Tarefa",
        "nl": "Naam voor taak-ID-veld",
        "fr": "Nom du champ ID de tâche",
        "it": "Nome per il campo ID attività",
        "es": "Nombre del campo ID de tarea",
        "pl": "Nazwa pola ID zadania",
        "zh-cn": "任务ID字段的名称"
      },
      "Name für Priorität Feld": {
        "en": "Name for priority field",
        "de": "Anzeige für das Prioritätsfeld",
        "ru": "Имя для поля приоритета",
        "pt": "Nome para o campo prioritário",
        "nl": "Naam voor prioriteitsveld",
        "fr": "Nom du champ de priorité",
        "it": "Nome per campo priorità",
        "es": "Nombre del campo de prioridad",
        "pl": "Nazwa pola priorytetowego",
        "zh-cn": "优先字段名称"
      },
      "Name für URL Feld": {
        "en": "Name for URL field",
        "de": "Anzeige für das URL-Feld",
        "ru": "Имя для поля URL",
        "pt": "Nome para o campo de URL",
        "nl": "Naam voor URL-veld",
        "fr": "Nom du champ URL",
        "it": "Nome per il campo URL",
        "es": "Nombre del campo URL",
        "pl": "Nazwa pola adresu URL",
        "zh-cn": "URL字段名称"
      },
      "Name für Project ID Feld": {
        "en": "Name for Project ID field",
        "de": "Anzeige für das Feld Projekt-ID",
        "ru": "Имя для поля ID проекта",
        "pt": "Nome para o campo de ID do projeto",
        "nl": "Naam voor het veld Project-ID",
        "fr": "Nom du champ ID de projet",
        "it": "Nome per il campo ID progetto",
        "es": "Nombre del campo ID del proyecto",
        "pl": "Nazwa pola ID projektu",
        "zh-cn": "项目ID字段的名称"
      },
      "Name für Comment Count Feld": {
        "en": "Name for Comment Count field",
        "de": "Anzeige für das Feld Anzahl der Kommentare",
        "ru": "Имя для поля количества комментариев",
        "pt": "Nome para o campo de contagem de comentários",
        "nl": "Naam voor het veld Aantal reacties",
        "fr": "Nom du champ Nombre de commentaires",
        "it": "Nome per il campo Conteggio commenti",
        "es": "Nombre del campo Recuento de comentarios",
        "pl": "Nazwa pola Liczba komentarzy",
        "zh-cn": "评论计数名称字段"
      },
      "Name für Parent ID Feld": {
        "en": "Name for Parent ID field",
        "de": "Anzeige für das Feld Eltern-ID",
        "ru": "Имя для поля родительского идентификатора",
        "pt": "Nome para o campo de ID pai",
        "nl": "Naam voor het veld Ouder-ID",
        "fr": "Nom du champ ID parent",
        "it": "Nome per il campo ID genitore",
        "es": "Nombre para el campo de identificación del padre",
        "pl": "Nazwa pola ID rodzica",
        "zh-cn": "家长ID字段的名称"
      },
      "Name for task field": {
        "en": "Name for task field",
        "de": "Anzeige für das Aufgabenfeld",
        "ru": "Имя для поля задачи",
        "pt": "Nome para o campo de tarefa",
        "nl": "Naam voor taakveld",
        "fr": "Nom du champ de tâche",
        "it": "Nome per il campo delle attività",
        "es": "Nombre del campo de la tarea",
        "pl": "Nazwa pola zadania",
        "zh-cn": "任务栏名称"
      },
      "Name for button": {
        "en": "Name for button",
        "de": "Anzeige für Button",
        "ru": "Название кнопки",
        "pt": "Nome para o botão",
        "nl": "Naam voor knop",
        "fr": "Nom du bouton",
        "it": "Nome per il pulsante",
        "es": "Nombre del botón",
        "pl": "Nazwa przycisku",
        "zh-cn": "按钮名称"
      },
      "Button for close task aktiv?": {
        "en": "Button aktiv?",
        "de": "Button aktiv?",
        "ru": "Кнопка закрытия задачи актив?",
        "pt": "Botão para fechar a tarefa aktiv?",
        "nl": "Knop voor afsluiten taak aktiv?",
        "fr": "Bouton pour fermer la tâche aktiv?",
        "it": "Pulsante per chiudere l'attività aktiv?",
        "es": "Botón para cerrar la tarea aktiv?",
        "pl": "Przycisk do zamykania zadań?",
        "zh-cn": "按钮关闭任务aktiv？"
      },
      "When no Todo, is the table visable?": {
        "en": "When no Todo, is the table visable?",
        "de": "Wenn kein Todo, ist die Tabelle sichtbar?",
        "ru": "Если нет Todo, видна ли таблица?",
        "pt": "Quando não há Todo, a mesa fica visível?",
        "nl": "Is de tafel zichtbaar als er geen Todo is?",
        "fr": "Quand pas de Todo, la table est-elle visible?",
        "it": "Quando non c'è niente da fare, il tavolo è visibile?",
        "es": "Cuando no hay Todo, ¿se ve la mesa?",
        "pl": "Jeśli nie ma zadań do wykonania, czy tabela jest widoczna?",
        "zh-cn": "如果没有待办事项，该表是否可见？"
      },
      "Name for no todo": {
        "en": "Display for no todo",
        "de": "Anzeige wenn kein Todo da ist",
        "ru": "Имя для no todo",
        "pt": "Nome para nenhuma tarefa",
        "nl": "Naam voor no todo",
        "fr": "Nom pour pas de todo",
        "it": "Nome per niente cose da fare",
        "es": "Nombre para no todo",
        "pl": "Nazwij brak rzeczy do zrobienia",
        "zh-cn": "待办事项名称"
      },
      "Todoist Settings": {
        "en": "Todoist Settings",
        "de": "Todoist Einstellungen",
        "ru": "Настройки Todoist",
        "pt": "Configurações de Todoist",
        "nl": "Todoist-instellingen",
        "fr": "Paramètres Todoist",
        "it": "Impostazioni di Todoist",
        "es": "Configuración de Todoist",
        "pl": "Ustawienia Todoist",
        "zh-cn": "Todoist设置"
      },
      "icon for Button": {
        "en": "icon for Button",
        "de": "Symbol für Button",
        "ru": "значок для кнопки",
        "pt": "ícone para botão",
        "nl": "pictogram voor knop",
        "fr": "icône pour Button",
        "it": "icona per Button",
        "es": "icono de botón",
        "pl": "ikona przycisku",
        "zh-cn": "按钮的图标"
      },
      "RAW Data": {
        "en": "RAW Data",
        "de": "Rohdaten",
        "ru": "Необработанные данные",
        "pt": "Dados não tratados",
        "nl": "Ruwe data",
        "fr": "Données brutes",
        "it": "Dati RAW",
        "es": "Datos RAW",
        "pl": "Surowe dane",
        "zh-cn": "原始数据"
      },
      "RAW Daten als Objekte anlegen": {
        "en": "RAW Data as object",
        "de": "Rohdaten als Objekt anlaegen",
        "ru": "RAW-данные как объект",
        "pt": "Dados RAW como objeto",
        "nl": "RAW-gegevens als object",
        "fr": "Données RAW en tant qu'objet",
        "it": "Dati RAW come oggetto",
        "es": "Datos RAW como objeto",
        "pl": "Surowe dane jako obiekt",
        "zh-cn": "RAW 数据作为对象"
      }
}    